language: c

compiler: 

  -gcc
  
before install:
  - sudo apt-get update
  - sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev
   
  
script:
  -echo "Reached Script Section"
  -gcc  HelloWorld.c -o output
  -./output
  
  
